//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programind.dal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Table_1
    {
        public int id { get; set; }
        [Required(ErrorMessage ="soyisim kýsmý boþ geçilemez")] 
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> present { get; set; }
    }
}
